version: "3.8"

services:

  traefik:
    image: "traefik:v2.3"
    command:
      - "--log.level=DEBUG"
      - "--accesslog"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik_default"
      - "--providers.docker.defaultRule=Host(`example.com`)"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"

  whoami:
    image: "traefik/whoami"
    deploy:
      replicas: 5
      placement:
        constraints:
          - "node.role!=manager"
      labels:
        - traefik.http.services.traefik-external-whoami.loadbalancer.server.port=80
        - traefik.enable=true
