services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - db:/data/db 
      - configdb:/data/configdb

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
   db: {}
   configdb: {}

